container:
  image: themattrix/tox-base

  additional_containers:
    - name: postgres
      image: postgres:latest
      port: 5432
      env:
        POSTGRES_DB: "potassium"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "secret"

check_task:
  env:
    DATABASE_NAME: "potassium"
    DATABASE_USER: "postgres"
    DATABASE_PASSWORD: "secret"
    DATABASE_HOST: "127.0.0.1"
    DATABASE_PORT: 5432
  script: tox
